config/routes.rb
Rails.application.routes.draw do

  root to: "talks#index"
  get 'search', to: 'talks#search'
  resources :talks, only: [:index,:show]
  resources :categories, only: [:index,:show]
  resources :subcategories, only: [:show]
  resources :speakers, only: [:index,:show]

  get '*path', controller: 'application', action: 'render_404'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bigcategory.rb
class Bigcategory < ApplicationRecord
  has_many :talks
  has_many :smallcategories
end

app/models/smallcategory.rb
class Smallcategory < ApplicationRecord
  belongs_to :bigcategory
  has_many :talks
end

app/models/speaker.rb
class Speaker < ApplicationRecord
  has_many :talks

  def self.search(search)
    if search
      where(['name LIKE ?', "%#{search}%"])
    end
  end
end

app/models/talk.rb
class Talk < ApplicationRecord
  # mount_uploader :thumbnail, ImageUploader
  belongs_to :bigcategory
  belongs_to :smallcategory
  belongs_to :speaker

  def self.search(search)
    if search
      where(['title LIKE ?', "%#{search}%"])
    end
  end

  def self.summery_search(search)
    if search
      where(['summary LIKE ?', "%#{search}%"])
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :relation_categories

  def relation_categories
    @categories = Bigcategory.order("RANDOM()")
  end

  rescue_from ActiveRecord::RecordNotFound, with: :render_404
  rescue_from ActionController::RoutingError, with: :render_404
  rescue_from Exception, with: :render_500

  def render_404
    render template: 'errors/error_404', status: 404, layout: 'application', content_type: 'text/html'
  end

  def render_500
    render template: 'errors/error_500', status: 500, layout: 'application', content_type: 'text/html'
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Bigcategory.all
  end

  def show
    @category = Bigcategory.find(params[:id])
  end
end

app/controllers/speakers_controller.rb
class SpeakersController < ApplicationController
  def index
    @speakers = Speaker.all
  end

  def show
    @speaker = Speaker.find(params[:id])
    @talks = Talk.order("RANDOM()")[0..11]
  end
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  def show
    @subcategory = Smallcategory.find(params[:id])
  end
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  def index
      @bigcategories = Bigcategory.order("RANDOM()")
  end

  def search
      @speakers = Speaker.search(params[:search])
      @talks = Talk.search(params[:search])
      @speakers_talks_volume = @talks.count
      @speakers.each do |speaker|
        @speakers_talks_volume += speaker.talks.count
      end
      @perhaps = Talk.summery_search(params[:search]) if @speakers_talks_volume == 0
  end

  def show
    @talk = Talk.find(params[:id])
    @relation_talk = @talk.smallcategory.talks.where.not(id: @talk.id).order("RANDOM()")[0..11]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: 'TEDRadio',
      title: "日本語音声で聞けるTEDメディア",
      reverse: true,
      charset: 'utf-8',
      description: "TEDRadioは、外国語のTEDでも日本語音声で聞けるTED日本語音声メディアです。字幕を見るために目が離せなくなっていたTEDも、楽に聞けるようになりました。有名TEDを是非日本語で聞いてみてください！",
      # keywords: 'キーワード',
      canonical: request.original_url,
      separator: '|',
      og: {
        site_name: 'TEDRadio',
        title: '日本語音声で聞けるTEDメディア',
        description: 'TEDRadioは、外国語のTEDでも日本語音声で聞けるTED日本語音声メディアです。字幕を見るために目が離せなくなっていたTEDも、楽に聞けるようになりました。有名TEDを是非日本語で聞いてみてください！',
        type: 'website',
        url: request.original_url,
        image: request.original_url+"tedradio_ogp.png",
        locale: 'ja_JP',
      },
      twitter: {
        card: 'summary_large_image',
        site: '@hatsu',
        title: "TEDRadio | 日本語音声で聞けるTEDメディア",
        description: "TEDRadioは、外国語のTEDでも日本語音声で聞けるTED日本語音声メディアです。字幕を見るために目が離せなくなっていたTEDも、楽に聞けるようになりました。有名TEDを是非日本語で聞いてみてください！",
        image: request.original_url+"tedradio_ogp.png",
        url: request.original_url
      }
    }
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/speakers_helper.rb
module SpeakersHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/talks_helper.rb
module TalksHelper
end

app/views/categories/index.html.erb
<h1>Categories#index</h1>

<% @categories.each do |category| %>
  <%= link_to category.name,category_path(category) %>
  <ul>
  <% category.smallcategories.each do |sub_category| %>
    <li><%= link_to sub_category.name,subcategory_path(sub_category) %></li>
  <% end %>
  </ul>
<% end %>

app/views/categories/show.html.erb
<% set_meta_tags title: @category.name+"カテゴリー",  og: { title: @category.name+ "カテゴリーのTEDRadioトーク"} ,twitter:{title: @category.name+ "カテゴリーのTEDRadioトーク"} %>

<div class="shadow_section">
  <section id="category_page" class="section_blok">
    <h1 class="page_title"><%= @category.name %>
    <br><span>(<%= @category.talks.count %>件)</span>
    </h1>
    <% @category.smallcategories.each do |category| %>
      <div class="shadow_section">
        <div class="category_talk_block section_block">
          <h3 class="category_title">
            <%= link_to category.name, subcategory_path(category) %><span>（<%= category.talks.count %>件）</span>
            <span class="to_category_page right">
              <%= link_to "もっと見る", subcategory_path(category) %>
            </span>
          </h3>
          <div class="talks_block row">
            <% category.talks.order("RANDOM()")[0..3].each do |talk| %>
              <div class="talk_block col s6 m3 card">
                <div class="talk_thumnbnail_cover card-image">
                  <%= image_tag(talk.thumbnail, :class => "activator") %>
                  <span class="take_time"><%= talk.taketime.strftime("%H:%M") %></span>

                  <span class="detail_desp_triger activator">内容</span>
                </div>
                <div class="card-content">
                  <span class="speaker_name">
                    <%= link_to talk.speaker.name,speaker_path(talk.speaker.id) %>
                  </span>
                  <br>
                  <%= link_to talk.title ,talk_path(talk) %>
                </div>
                <div class="card-reveal">
                  <span class="card-title">
                    内容<i class="fas fa-times right"></i>
                  </span>
                  <p class="talk_title"><%= link_to talk.title ,talk_path(talk) %></p>
                  <p class="talk_summary"><%= talk.summary %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= display_meta_tags(default_meta_tags) %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="<%= root_url%>favicons/favicon.ico">
    <link rel="icon" type="image/vnd.microsoft.icon" href="<%= root_url %>favicons/favicon.ico">
    <link rel="apple-touch-icon" sizes="57x57" href="<%= root_url %>favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="<%= root_url %>favicons/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="<%= root_url %>favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="<%= root_url %>favicons/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="<%= root_url %>favicons/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="<%= root_url %>favicons/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="<%= root_url %>favicons/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="<%= root_url %>favicons/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="<%= root_url %>favicons/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="36x36" href="<%= root_url %>favicons/android-chrome-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="<%= root_url %>favicons/android-chrome-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="<%= root_url %>favicons/android-chrome-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= root_url %>favicons/android-chrome-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="<%= root_url %>favicons/android-chrome-128x128.png">
    <link rel="icon" type="image/png" sizes="144x144" href="<%= root_url %>favicons/android-chrome-144x144.png">
    <link rel="icon" type="image/png" sizes="152x152" href="<%= root_url %>favicons/android-chrome-152x152.png">
    <link rel="icon" type="image/png" sizes="192x192" href="<%= root_url %>favicons/android-chrome-192x192.png">
    <link rel="icon" type="image/png" sizes="256x256" href="<%= root_url %>favicons/android-chrome-256x256.png">
    <link rel="icon" type="image/png" sizes="384x384" href="<%= root_url %>favicons/android-chrome-384x384.png">
    <link rel="icon" type="image/png" sizes="512x512" href="<%= root_url %>favicons/android-chrome-512x512.png">
    <link rel="icon" type="image/png" sizes="36x36" href="<%= root_url %>favicons/icon-36x36.png">
    <link rel="icon" type="image/png" sizes="48x48" href="<%= root_url %>favicons/icon-48x48.png">
    <link rel="icon" type="image/png" sizes="72x72" href="<%= root_url %>favicons/icon-72x72.png">
    <link rel="icon" type="image/png" sizes="96x96" href="<%= root_url %>favicons/icon-96x96.png">
    <link rel="icon" type="image/png" sizes="128x128" href="<%= root_url %>favicons/icon-128x128.png">
    <link rel="icon" type="image/png" sizes="144x144" href="<%= root_url %>favicons/icon-144x144.png">
    <link rel="icon" type="image/png" sizes="152x152" href="<%= root_url %>favicons/icon-152x152.png">
    <link rel="icon" type="image/png" sizes="160x160" href="<%= root_url %>favicons/icon-160x160.png">
    <link rel="icon" type="image/png" sizes="192x192" href="<%= root_url %>favicons/icon-192x192.png">
    <link rel="icon" type="image/png" sizes="196x196" href="<%= root_url %>favicons/icon-196x196.png">
    <link rel="icon" type="image/png" sizes="256x256" href="<%= root_url %>favicons/icon-256x256.png">
    <link rel="icon" type="image/png" sizes="384x384" href="<%= root_url %>favicons/icon-384x384.png">
    <link rel="icon" type="image/png" sizes="512x512" href="<%= root_url %>favicons/icon-512x512.png">
    <link rel="icon" type="image/png" sizes="16x16" href="<%= root_url %>favicons/icon-16x16.png">
    <link rel="icon" type="image/png" sizes="24x24" href="<%= root_url %>favicons/icon-24x24.png">
    <link rel="icon" type="image/png" sizes="32x32" href="<%= root_url %>favicons/icon-32x32.png">

    <!-- //Facebook用 -->
    <meta property="fb:app_id" content="2219201654987813" />
    <meta property="article:publisher" content="<%= root_url%>" />

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v3.2&appId=1104643199674110&autoLogAppEvents=1';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    <header>
      <h1><%= link_to "TEDRadio",root_path %></h1>
      <i class="fas fa-search form_to_appear"></i>
      <div class="search_form row">
        <i class="fas fa-search form_to_close"></i>
        <%= form_tag(search_path, :method => 'get' ) do %>
          <%= text_field_tag :search,params[:search],class: 'col s9 offset-s1 search_field' %>
          <%= submit_tag '検索', class: 'btn col s2 search_btn' %>
        <% end %>
      </div>
    </header>
    <%= yield %>

    <div class="shadow_section">
      <section id="relation_category" class="section_block">
        <h2 class="relation_title">カテゴリー一覧</h2>
        <div class="talks_block">
          <ul class="collapsible">
            <% @categories.each do |category| %>
              <li class="row">
                <div class="collapsible-header col s11">
                  <i class="fas fa-plus"></i><%= category.name %>
                  <span>(<%= category.talks.count %>)</span>
                </div>
                <%= link_to category_path(category),class: 'to_category_link s1' do %>
                  <i class="material-icons">send</i>
                <% end %>
                <div class="collapsible-body">
                  <ul class="collection">
                    <% category.smallcategories.each do |subcategory| %>
                      <li class="collection-item">
                        <%= link_to subcategory_path(subcategory), class: 'subcategory_link' do %>
                          <%= subcategory.name %>
                          <span>(<%= subcategory.talks.count %>)</span>
                        <% end %>
                        <%= link_to subcategory_path(subcategory),class: 'secondary-content subcategory_link' do %>
                          <i class="material-icons">send</i>
                        <% end %>
                      </li>
                    <% end %>
                  </ul>
                </div>
              </li>
            <% end %>
          </ul>
        </div>
      </section>
    </div>

    <footer>
      <h2>シェアする</h2>
      <div class="footer_border_top"></div>
      <ul class="sns_block row">
        <li class="col s4">
          <a href="https://twitter.com/share?url=<%= root_url %>&text=TEDRadio - 日本語音声で聞けるTEDメディア #TEDRadio" target="_blank" class="twitter sns">
            <i class="fab fa-twitter"></i>
          </a>
        </li>
        <li class="col s4">
          <a href="https://www.facebook.com/share.php?u=<%= root_url %>&text=TEDRadio | 日本語音声で聞けるTEDメディア" target="_blank" class="facebook sns">
            <i class="fab fa-facebook-f"></i>
          </a>
        </li>
        <li class="col s4">
          <a href="http://b.hatena.ne.jp/entry/<%= root_url %>" data-hatena-bookmark-layout="touch" title="このエントリーをはてなブックマークに追加" target="_blank" class="hatena sns">
            B!
          </a>
        </li>
      </ul>
      <div class="info_block">
        <a href="https://twitter.com/hatsu_38" target="_blank"><i class="fas fa-play-circle"></i>運営者</a>
      </div>
      <p class="footer_copy">
      © Copyright 2018 hastu All rights reserved.
      </p>
    </footer>
  </body>
</html>

app/views/speakers/index.html.erb
<h1>Speakers#index</h1>
<% @speakers[0..9].each do |speaker| %>
  <%= speaker.name %>
<% end %>

app/views/subcategories/show.html.erb
<% set_meta_tags title: @subcategory.name+"カテゴリー",  og: { title: @subcategory.name+"カテゴリーのTEDRadioトーク"},twitter:{title: @subcategory.name + "カテゴリーのTEDRadioトーク"}  %>
<div class="shadow_section">
  <section id="sub_category_page" class="section_block">
    <h1 class="page_title"><%= @subcategory.name %>
    <br><span>(<%= @subcategory.talks.count %>件)</span>
    </h1>
    <ul class="row">
      <% @subcategory.talks.each do |talk| %>
        <div class="talks_block col s6 m3">
          <div class="talk_block card">
            <div class="talk_thumnbnail_cover card-image">
              <%= image_tag(talk.thumbnail, :class => "activator") %>
              <span class="take_time"><%= talk.taketime.strftime("%H:%M") %></span>

              <span class="detail_desp_triger activator">内容</span>
            </div>
            <div class="card-content">
              <span class="speaker_name">
                <%= link_to talk.speaker.name,speaker_path(talk.speaker.id) %>
              </span>
              <br>
              <%= link_to talk.title ,talk_path(talk) %>
            </div>
            <div class="card-reveal">
              <span class="card-title">
                内容<i class="fas fa-times right"></i>
              </span>
              <p class="talk_title"><%= link_to talk.title ,talk_path(talk) %></p>
              <p class="talk_summary"><%= talk.summary %></p>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </section>
</div>

app/views/talks/index.html.erb
<section id="top">
  <div class="shadow_section">
      <% @bigcategories.each do |category| %>
        <div class="category_talk_block section_block">
          <h2 class="category_title">
            <%= link_to category.name, category_path(category) %><span>（<%= category.talks.count %>件）</span>
            <span class="to_category_page right">
              <%= link_to "もっと見る", category_path(category) %>
            </span>
          </h2>
          <div class="talks_block row">
            <% category.talks.order("RANDOM()")[0..3].each do |talk| %>
              <div class="talk_block col s6 m3 card">
                <div class="talk_thumnbnail_cover card-image">
                  <%= image_tag(talk.thumbnail, :class => "activator") %>
                  <span class="take_time"><%= talk.taketime.strftime("%H:%M") %></span>
                  <span class="detail_desp_triger activator">内容</span>
                </div>
                <div class="card-content">
                  <span class="speaker_name">
                    <%= link_to talk.speaker.name,speaker_path(talk.speaker.id) %>
                  </span>
                  <br>
                  <%= link_to talk.title ,talk_path(talk) %>
                </div>
                <div class="card-reveal">
                  <span class="card-title">
                    内容<i class="fas fa-times right"></i>
                  </span>
                  <p class="talk_title"><%= link_to talk.title ,talk_path(talk) %></p>
                  <p class="talk_summary"><%= talk.summary %></p>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      <% end %>
  </div>
</section>

app/views/talks/show.html.erb
<% set_meta_tags title: @talk.speaker.name + "の話す" + @talk.title, description: @talk.summary,  og: { title: @talk.speaker.name + "の話す" + @talk.title, description: @talk.summary,image: @talk.thumbnail,type: "article"},twitter:{title: @talk.speaker.name + "の話す" + @talk.title , description: @talk.summary,image: @talk.thumbnail} %>

<div class="shadow_section">
  <section id="show" class="section_block">
    <div class="talk_thumnbnail_cover">
      <%= image_tag @talk.thumbnail %>
      <span id="start_btn" class="start_radio_btn"><i class="fas fa-play fa-2x"></i></span>
      <span id="resume_btn" class="resume_radio_btn"><i class="fas fa-play fa-2x"></i></span>
      <span id="stop_btn" class="stop_radio_btn"><i class="fas fa-equals fa-2x fa-rotate-90"></i></span>
      <!-- <div id="pass_time" class="now_time"> -->
      <!--   <span id="pass_min">00</span>:<span id="pass_sec">00</span> -->
      <!-- </div> -->
      <span class="take_time"><%= @talk.taketime.strftime("%H:%M") %></span>
      <div class="progress">
        <div class="determinate" style="width: 0%"></div>
      </div>
      <p class="flow_text"></p>
    </div>
    <div class="talk_info container">
      <h1><%= @talk.title %></h1>
    </div>
    <div class="talk_share_btn">
      <a href="https://twitter.com/share?ref_src=twsrc%5Etfw" class="twitter-share-button" data-show-count="false">Tweet</a>
      <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
      <div class="fb-share-button" data-href="<%=request.url %>" data-layout="button" data-size="small" data-mobile-iframe="true">
        <a target="_blank" href="https://www.facebook.com/sharer/sharer.php?u=<%=request.url %>&amp;src=sdkpreparse" class="fb-xfbml-parse-ignore">シェア</a>
      </div>
    </div>
    <div class="talk_detail_info">
      <%= link_to @talk.speaker.name,speaker_path(@talk.speaker.id) %>
      <span class="right"><%= @talk.date.strftime("%Y/%m/%d") %></span>
    </div>
    <div class="talk_fixer">
      <div class="left talk_speed">
        <div id="normal_speed" class="chip">×1.0</div>
        <div id="little_high_speed" class="chip">×1.2</div>
        <div id="high_speed" class="chip">×1.5</div>
      </div>
      <div class="categories_name right">
        <div class="chip">
          <%= link_to @talk.bigcategory.name,category_path(@talk.bigcategory.id) %>
        </div>
        <div class="chip">
          <%= link_to @talk.smallcategory.name,subcategory_path(@talk.smallcategory.id) %>
        </div>
      </div>
    </div>
    <div class="summary container">
      <%= simple_format(@talk.summary) %>
    </div>
    <div id="sentence" class="sentence container">
      <%= simple_format(@talk.sentence) %>
    </div>
  </section>
</div>

<div class="shadow_section">
  <section id="relation_talk" class="row section_block">
    <h2 class="relation_title">関連トーク</h2>
    <div class="talks_block">
      <% @relation_talk.each do |talk| %>
        <div class="talk_block col s6 m3 card">
          <div class="talk_thumnbnail_cover card-image">
            <%= image_tag(talk.thumbnail, :class => "activator") %>
            <!-- <span class="start_radio_btn"><i class="fas fa&#45;play fa&#45;2x"></i></span> -->
            <span class="take_time"><%= talk.taketime.strftime("%H:%M") %></span>
            <span class="detail_desp_triger activator">内容</span>
          </div>
          <div class="card-content">
            <span class="speaker_name">
              <%= link_to talk.speaker.name,speaker_path(talk.speaker.id) %>
            </span>
            <br>
            <%= link_to talk.title ,talk_path(talk) %>
          </div>
          <div class="card-reveal">
            <span class="card-title">
              内容<i class="fas fa-times right"></i>
            </span>
            <p class="talk_title"><%= link_to talk.title ,talk_path(talk) %></p>
            <p class="talk_summary"><%= talk.summary %></p>
          </div>
        </div>
      <% end %>
    </div>
  </section>
</div>

<script>
$(function() {
  var sec = 0;
  var min = 0;
  var timer = 0;
  var speed = 1.1;
  // 準備 $voicesを取得したいだけなのだけれども
  $voise        = null;
  $voiseName    = 'Google 日本語';
  $voices       = speechSynthesis.getVoices();
  $synthes      = new SpeechSynthesisUtterance();

  // SpeechSynthesisUtterance()に時間かかるから様子みる
  $repeat  = setInterval(function() {
    if($synthes){
      $voices  = speechSynthesis.getVoices();
      clearInterval($repeat);
    }
  }, 300);

  // 読み上げ
  function say(msg,speed){
    $voise = $.grep($voices, function(n, i){return n.name == $voiseName})[0];
    $synthes.voice = $voise;                  // 音声の設定
    $synthes.rate = speed;
    speechSynthesis.cancel();                 // かぶった読み停止
    $synthes.text  = msg;                     // 読む内容
    // $synthes.lang = 'ja-JP';
    speechSynthesis.speak($synthes);          // 喋れ
    $(".flow_text").text(msg);
  }

  function change_speed(speed){
    $synthes.rate = speed;
  }

  function stop($synthes){
    speechSynthesis.pause($synthes);
  }

  function resume($synthes){
    speechSynthesis.resume($synthes);
  }
  function pass_count(){
    if(sec< 10){
      $("#pass_sec").text("0"+parseInt(sec));
    }else{
      $("#pass_sec").text(parseInt(sec));
    }
    if(min< 10){
      $("#pass_min").text("0"+parseInt(min));
    }else{
      $("#pass_min").text(parseInt(min));
    }
    sec++;
    if(sec == 60){
      sec = 0;
      min++;
    };
  }
  function speed_change_color(speed){
    switch(speed){
      case 1.1:
        $("#normal_speed").addClass("active");
        $("#little_high_speed").removeClass("active");
        $("#high_speed").removeClass("active");
        break;
      case 1.2:
        $("#normal_speed").removeClass("active");
        $("#little_high_speed").addClass("active");
        $("#high_speed").removeClass("active");
        break;
      case 1.5:
        $("#normal_speed").removeClass("active");
        $("#little_high_speed").removeClass("active");
        $("#high_speed").addClass("active");
        break;
    }
  }

  function progressbar_style(i,all){
    var progress_rate = (i/all)*100;
    $(".determinate").css("width",progress_rate+"%");
  }

  // ボタン動作
  $('#start_btn').on('click',function(){
    $(this).hide();
    $("#stop_btn").show();
    speed_change_color(speed);
    timer = setInterval(pass_count,1000);
    var i = 0;
    var last_say_num = $("#sentence p").length;
    say($("#sentence p").eq(i).text(),speed);
    $synthes.onend = function (event) {
      if(i == last_say_num){
        return false;
      }
      i++;
      progressbar_style(i,last_say_num);
      speed_change_color(speed);
      say($("#sentence p").eq(i).text(),speed);
      $synthes.onend;
    };
  });

  $('#normal_speed').on('click',function(){
    speed = 1.1;
  });
  $('#little_high_speed').on('click',function(){
    speed = 1.2;
  });
  $('#high_speed').on('click',function(){
    speed = 1.5;
  });

  $(function () {
    var ted_sentence = $("#sentence").html();
    var sentence_fixed = ted_sentence.replace(/。/g, "。</p><p>");
    var sentence_fixed = sentence_fixed.replace(/？/g, "？</p><p>");
    var sentence_fixed = sentence_fixed.replace(/」/g, "」</p><p>");
    $("#sentence").html(sentence_fixed);
  });


  $("#stop_btn").on('click',function(){
    stop($synthes);
    clearInterval(timer);
    $(this).hide();
    $("#resume_btn").show();
  });

  $("#resume_btn").on('click',function(){
    resume($synthes);
    timer = setInterval(pass_count,1000);
    $(this).hide();
    $("#stop_btn").show();
  });
});
</script>